version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:9441984210@localhost:5432/kvt"
      REDIS_URL: "redis://default:c75207c8f0684fc58ebf8eeb310ea66d@gusc1-sharp-osprey-31084.upstash.io:31084"
      PORT: 3000
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kvt
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
